IF	//Aerie Romance Throne of Bhaal Rest. EXTEND_BOTTOM ~aeri25.bcs~
	Global("AerieRomanceActive","GLOBAL",2)
	See(Player1)
	CombatCounter(0)
	Global("ExpLoveTalk","LOCALS",3)
	Global("YF_restcheck","GLOBAL",0)
THEN
	RESPONSE #100
	SetGlobal("YF_restcheck","GLOBAL",1)
END

IF	
	Global("ExpLoveTalk","LOCALS",4)
	Global("YF_ExpLoveTalk4","LOCALS",0)
THEN
	RESPONSE #100
	SetGlobal("YF_restcheck","GLOBAL",2)
	SetGlobal("YF_ExpLoveTalk4","LOCALS",1)
END
