
//ClaraBanter Trigger
IF 
	InParty("_bClara")
	InParty("DORN") 
	InMyArea("_bClara") 
	!StateCheck("DORN",CD_STATE_NOTVALID) 
	!StateCheck("_bClara",CD_STATE_NOTVALID) 
	Global("_BBCLARADORN","GLOBAL",2)
	!Global("DornRomanceActive","GLOBAL",2)
	OR(3)
	AreaCheck("AR6400")
	AreaCheck("AR6300")
	AreaType(FOREST)
	Global("_brestcheck","GLOBAL",0)
THEN
	RESPONSE #100
	SetGlobal("_brestcheck","GLOBAL",2)
	SetGlobal("_BBCLARADORN","GLOBAL",3)
END