
//ClaraBanter Trigger
IF 
	InParty("_bClara") 
	InMyArea("_bClara")
	InParty("DORN")
	!StateCheck("DORN",CD_STATE_NOTVALID) 
	!StateCheck("_bClara",CD_STATE_NOTVALID) 
	Global("_BBCLARADORN","GLOBAL",2)
	!Global("DornRomanceActive","GLOBAL",2)
	OR(2)
	AreaCheck("AR6300")
	AreaType(FOREST)
	Global("_brestcheck","GLOBAL",0)
THEN
	RESPONSE #100
	SetGlobal("_brestcheck","GLOBAL",2)
	SetGlobal("_BBCLARADORN","GLOBAL",3)
END