
//ClaraBanter Trigger
IF 
	InParty("YF_Clara")
	InParty("DORN") 
	InMyArea("YF_Clara") 
	!StateCheck("DORN",CD_STATE_NOTVALID) 
	!StateCheck("YF_Clara",CD_STATE_NOTVALID) 
	Global("YF_BCLARADORN","GLOBAL",2)
	!Global("DornRomanceActive","GLOBAL",2)
	OR(3)
	AreaCheck("AR6400")
	AreaCheck("AR6300")
	AreaType(FOREST)
	Global("YF_restcheck","GLOBAL",0)
THEN
	RESPONSE #100
	SetGlobal("YF_restcheck","GLOBAL",2)
	SetGlobal("YF_BCLARADORN","GLOBAL",3)
END